site_name: Лабораторные работы по веб-программированию
site_description: Отчёты по лабораторным работам 1–3
remote_branch: gh-pages
remote_name: course-fork
theme:
  name: material
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
      check_paths: true
nav:
  - Главная: index.md
  - Лабораторная работа 1: labs/lr1.md
  - Лабораторная работа 2: labs/lr2.md
  - Лабораторная работа 3: labs/lr3.md
